---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-clone.yaml
  - list-directory.yaml
  - send-to-gchat.yaml
  - write-file.yaml
  - get-kubeconfig.yaml
  - buildah.yaml
  - set-tag.yaml
  - deploy-gotests.yaml
